#context-based or route-based application LB
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: context-controller
  annotations:
    kubernetes.io/ingress.class: "gce" 
spec:
  # ingressClassName: gce
  defaultBackend:
    service:
      name: deploy-ingress-green
      port:
        number: 80 #serviceport
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/blue"
        backend:
          service:
            name: deploy-ingress-blue
            port:
              number: 80
      - pathType: Prefix
        path: "/orange"
        backend:
          service:
            name: deploy-ingress-orange
            port:
              number: 80