apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: host-based-ingress
spec:
  rules:
  - host: green.nagasaikonderu.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: deploy-ingress-green #it should match service name you gave
            port:
              number: 80
  - host: blue.nagasaikonderu.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: deploy-ingress-blue
            port:
              number: 80
  - host: orange.nagasaikonderu.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: deploy-ingress-orange
            port:
              number: 80